### ISSUE TITLE
Clarification about the direction of the WebOS QtWayland

### ISSUE THREAD

**Issue by basyskom-meerkoetter** [webosose/qtwayland#1]
I am wondering about the future of the WebOS QtWayland codebase.

It seems to be a fork of upstream QtWayland. The fork was done/is keept in sync with the upstream 5.12.x release. I assume this is done deliberately so the license is GPL/LGPL/Commercial. Is this correct?

The overall WebOS platform is moving forward regarding Qt. Does the project plan to maintain this fork long-term or will this repo also be switched over to a QtWayland that is dual-licensed?

**Comment by basyskom-meerkoetter** [comment]
@ElvisLee and @jaeyoonjung do you habe any insight here?

**Comment by jaeyoonjung** [comment]
Yes, webosose/qtwayland repo is a fork of upstream qtwayland and follows the original license.
Since webOS OSE 2.12.0 however, we use the upstream qtwayland from meta-qt6 and webosose/qtwayland repo is no longer used.
https://www.webosose.org/about/release-notes/webos-ose-2-12-0-release-notes/
The plan is to follow upstream qtwayland through meta-qt6 going forward.

Hope this answers your question.

**Comment by basyskom-meerkoetter** [comment]
Thank you for the clarification
